language: php

php:
    - '7.1'

services:
  - postgresql

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - psql -c "CREATE DATABASE testing_db;" -U postgres

script:
  - mkdir -p ./tests/build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

